# Generated by Django 4.2.7 on 2023-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('pdetails', models.CharField(max_length=200, verbose_name='Product Details')),
                ('category', models.CharField(max_length=100, verbose_name='Catogory Of Product')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
            ],
        ),
    ]
