# Generated by Django 4.2.7 on 2023-12-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_product_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'COFFEE'), (2, 'DRINKS'), (3, 'DESSERT'), (4, 'BURGUR')]),
        ),
    ]
