# Generated by Django 4.2.7 on 2023-12-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'COFFEE'), (2, 'DRINKS'), (3, 'DESSERTS'), (4, 'BURGUR')]),
        ),
    ]
